# Workflow for CMake build and test on Ubuntu.
name: Ubuntu CMake build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # CMake build type -- Release, Debug, RelWithDebInfo, etc.
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/benjaminjeliot/docker-ubuntu-dev:main

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake project
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_UNIT_TESTS:BOOL=ON -DENABLE_DOCUMENTATION:BOOL=ON

    - name: Build
      # Build CMake project
      run: |
        ls ${{github.workspace}}/build
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      # Run CMake tests with CTest
      run: |
        cd ${{github.workspace}}/build
        ls
        ctest --no-tests=error --build-config ${{env.BUILD_TYPE}}
